name: Build and Release

on:
  workflow_dispatch:
    inputs:
      code_zip_url:
        description: "Firebase link to the ZIP file containing the Flutter app code"
        required: true

jobs:
  # Download and unzip the Flutter code
  fetch-flutter-code:
    name: Fetch Flutter Code
    runs-on: ubuntu-latest
    outputs:
      code-path: ${{ steps.extract.outputs.code-path }}
    steps:
      - name: Download Flutter App Code from Firebase
        run: |
          # Download the ZIP file
          curl -L "${{ github.event.inputs.code_zip_url }}" -o flutter_app.zip
          # Quick check to confirm the file is present
          ls -l flutter_app.zip || true
          file flutter_app.zip || true

      - name: Unzip Flutter App Code
        id: extract
        run: |
          # Remove everything except .github, the '.' directory, and flutter_app.zip
          find . -maxdepth 1 ! -name '.github' ! -name '.' ! -name 'flutter_app.zip' -exec rm -rf {} +
          
          # Unzip into current directory
          unzip -o flutter_app.zip -d .
          echo "code-path=." >> $GITHUB_OUTPUT

  build-android:
    name: Android Build
    runs-on: ubuntu-latest
    needs: fetch-flutter-code
    steps:
      - name: Use Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter build apk --release

      - name: Upload APK Artifact
        # Vendored upload-artifact action in .github/actions/upload-artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: iOS Build
    runs-on: macos-latest
    needs: fetch-flutter-code
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - name: Build iOS Release
        run: flutter build ios --release --no-codesign

      - name: Create Payload folder
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move Runner.app into Payload
        run: mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA Artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ios-ipa
          path: build/ios/iphoneos/FlutterIpaExport.ipa

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]
    steps:
      # IMPORTANT: We must check out the repo in this job so the local actions (./.github/actions/...) exist
      - uses: actions/checkout@v3

      - name: Download Android APK
        uses: ./.github/actions/download-artifact
        with:
          name: android-apk
          path: artifacts

      - name: Download iOS IPA
        uses: ./.github/actions/download-artifact
        with:
          name: ios-ipa
          path: artifacts

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/*
          file_glob: true
          tag: v1.0
          overwrite: true
          body: "This is the first release with both Android and iOS binaries."
